export { default as App } from './App';
export { default as Questions } from './Questions';
export { default as Question } from './Question';
export { default as Nav } from './Nav';
export { default as Pagination } from './Pagination';
export { default as Answer } from './Answer';
export { default as Answers } from './Answers';
export { default as DetailQuestion } from './DetailQuestion';
export { default as ContentQuestion } from './ContentQuestion';
